### PR TITLE
Initial Cmake configuration

### PR DESCRIPTION
**Pull request by hobbes1069**
Wow, so it doesn't have to be a fork to do a pull request... 

It picked up the fact I copied the Makefile to CMakeLists.txt so merging this will remove Makefile but I have pretty much all of the basic functionality covered including fetching the lpcnet stuff.

### CODE REVIEW

**Comment by drowe67** [comment]
Thanks @hobbes1069 - looking good.  Just hit this snag:
```
$ mkdir build_linux $$ cd build_linux && cmake ../
-- avx processor flags found.
CMake Error at CMakeLists.txt:34 (include):
  include could not find load file:

    FetchContent

CMake Error at CMakeLists.txt:35 (FetchContent_Declare):
  Unknown CMake command "FetchContent_Declare".

```

**Comment by hobbes1069** [comment]
Hmm... What version of CMake are you running?

**Comment by hobbes1069** [comment]
Looks like it was added in 3.11.4... I hate to require something that new because it does exactly what we want.

**Comment by drowe67** [comment]
cmake version 3.9.1

**Comment by drowe67** [comment]
@hobbes1069 Well we could specify a minimum cmake version, or provide instructions on how to get the latest (bearing in mind it will be built on different platforms).  Just let me know how you would like to handle it.  I'm off to $dayjob now .....

**Comment by hobbes1069** [comment]
Give this a try when you can.

**Comment by drowe67** [comment]
Thanks, made it a bit further:

```
tar: /home/david/tmp/LPCNet/build_linux/src: Cannot open: No such file or directory
tar: Error is not recoverable: exiting now
-- Configuring done
CMake Error at src/CMakeLists.txt:20 (add_library):
  Cannot find source file:

    /home/david/tmp/LPCNet/build_linux/src/nnet_data.c
```

BTW can you try the examples at the top of README.md on yr machine pls?  Be interested to see if it runs OK in real time

**Comment by drowe67** [comment]
@hobbes1069 OK I messed around and have it working (src wasn't being created until after the un-tar) - pls feel free to edit if I've messed up anywhere!

1. Is it possible to have shared libs as well pls?
1. Will it work on a Windows X-compile?

**Comment by hobbes1069** [comment]
Ok, moving the set(lpcnet_SOURCE_DIR ${CMAKE_BINARY_DIR}/src) outside of the conditional will break the FetchContent method since it sets that for you and uses a different directory structure.

Also, I'm not sure what the purpose of moving the add_subdirectory to before pulling the lpcnet archive is for. If you're starting from scratch the freedv library will look for the sources and they won't be there yet.

**Comment by hobbes1069** [comment]
Ok, I moved the set(lpcnet... to the top of the conditional and changed it to look for the existence of ${CMAKE_BINARY_DIR}j/src instead of the archive, because that's really what we care about anyway.

And mnet_data.c needs to be prefixed with it's location because it's in the binary dir not the source dir. I'm not sure how that worked for you.

**Comment by hobbes1069** [comment]
Ok, I temporarily changed the conditional from VERSION_LESS to VERSION_GREATER to test both methods and they both work for me.

**Comment by hobbes1069** [comment]
Ok, back to your two questions...

1. The freedv library? It's a little bit of a pain but I can build both static and shared, or do you just want the ability to do one or the other?
2. Haven't gotten that far yet. I still need to port over some stuff from codec2 (like the check for doing in source builds.) Right now I'm not even checking for the existence of the codec2 library, I'm just assuming it's available.

**Comment by drowe67** [comment]
> Also, I'm not sure what the purpose of moving the add_subdirectory to before pulling the lpcnet archive is for. If you're starting from scratch the freedv library will look for the sources and they won't be there yet.

You can't un-tar to a directory that doesn't exist yet ... just tried the latest and back to original error:
```
-- [download 99% complete]
-- [download 100% complete]
tar: /home/david/tmp/LPCNet/build_linux/src: Cannot open: No such file or directory
tar: Error is not recoverable: exiting now
-- Configuring done
CMake Error at src/CMakeLists.txt:20 (add_library):

```
This is a subtle bug - you may have tested it with build_linux/src already created.  I test like this:
```
david@penetrator:~/tmp/LPCNet$ rm -rf build_linux && mkdir build_linux && cd build_linux && cmake ..
```

**Comment by hobbes1069** [comment]
Ahh... I can fix that using a cmake internal command.

**Comment by drowe67** [comment]
> Ok, back to your two questions...
> 
>     1. The freedv library? It's a little bit of a pain but I can build both static and shared, or do you just want the ability to do one or the other?

The lpcnet-freedv library we are creating in this PR.  The idea is this will be another "codec" that can be linked with codec2, to support a new FreeDV mode. Hmm, good question about either/or.  I just figure since we can build .so's and DLLs with Codec 2 we need a similar approach here.  Maybe handle it the same way as codec2?  I guess a shared lib will be most common if we want to run-time link it with codec2.

>     2. Haven't gotten that far yet. I still need to port over some stuff from codec2 (like the check for doing in source builds.) Right now I'm not even checking for the existence of the codec2 library, I'm just assuming it's available.

Cool. The end game is somehow linking it with freedv-gui on Windows.  However what you've got already is fine for where we are at in current development, i.e. coding up a freedv_api mode and linking lpcnet-freedv to codec2.  Thanks :+1:

**Comment by hobbes1069** [comment]
If that works then we should go ahead and merge I think. Unless you want me to go ahead and change the library. All that needs to be done is removing the STATIC and it will revert to whatever is set for BUILD_SHARED_LIBS=[TRUE/FALSE].

**Comment by drowe67** [comment]
> If that works then we should go ahead and merge I think. Unless you want me to go ahead and change the library. All that needs to be done is removing the STATIC and it will revert to whatever is set for BUILD_SHARED_LIBS=[TRUE/FALSE].

Thanks Richard that works well.  Sure, I'll go ahead and merge.  Noted on building shared - will try that some time.  Thanks so much for your help :+1:

**Pull request merged**
