### PR TITLE
Use local model data archive if available.

### PR DESCRIPTION
**Pull request by hobbes1069**
This makes packaging easier.

### CODE REVIEW

**Comment by doronbehar** [comment]
Thanks @hobbes1069 I've managed to make our build work with the patch here. It wasn't super trivial though, so it'd be nice to have this documented somehow.

**Comment by hobbes1069** [comment]
Updating the README is simple enough, but how often will the model data change? When it does we would have to remember to update the URL in the README... Another option would be to use a redirect. It may be as easy as creating a symbolic link between the latest data file, something like:

`ln -s lpcnet_191005_v1.0.tgz lpcnet_latest.tgz`

I need to check if apache automatically treats that as a redirect or not... Then when new model data is here, you just update the link.

**Comment by hobbes1069** [comment]
Ok, redirects are a little more complicated, so the file downloaded would end up being lpcnet_latest.tgz, I don't see that as a huge issue. Thoughts?

**Comment by doronbehar** [comment]
Redirects will be a good improvement, but as a start, I was really thinking of just adding [here](https://github.com/drowe67/LPCNet#ctests) a note indicating that the test data can be retrieved either automatically via cmake's build process or via http://rowetel.com/downloads/deep/ .

But, that web page needs to be configured at least to show the files available in that directory as in http://ftpmirror.gnu.org/hello/

**Comment by doronbehar** [comment]
Oh and perhaps more importantly, to mention that it should be downloaded to `build/` without extracting that tar file before building. I learned that after reading the `CMakeLists.txt` file - that's what I meant that isn't trivial.

**Comment by hobbes1069** [comment]
I need to think about this some more. Also, I'm working out how to handle packaging. This shouldn't get packaged as a separately library as its sole purpose is for freedv mode 2020.

**Pull request merged**
