### PR TITLE
fix cmake configuration file name

### PR DESCRIPTION
**Pull request by ra1nb0w**
fix installed cmake configuration as requested by freedv-gui

### CODE REVIEW

**Comment by hobbes1069** [comment]
I don't have any real objection to this, I was just trying to keep the file names short since you have to cross build codec2 and lpcnetfreedv. Please make sure the documentation is updated as well.

**Comment by ra1nb0w** [comment]
You can maintain the short name but you need to change [freedv-gui](https://github.com/drowe67/freedv-gui/blob/master/CMakeLists.txt#L257); I don't like `lpcnet` because it creates confusion with the upstream project and it generates a name collision.

After this patch we also need to harmonise https://github.com/drowe67/codec2/blob/master/CMakeLists.txt#L207

This patch works only when you are using installed codec2/lpcnetfreedv and it shouldn't touch other way of building.

**Comment by ra1nb0w** [comment]
Note: I don't find any line in doc about this aspect.

**Comment by ra1nb0w** [comment]
therefore, which way we take? :)

**Comment by hobbes1069** [comment]
Ok, maybe the export target name doesn't matter? When I first looked at this I was 8000 miles from home. Have you completed a build with codec2 without error?

**Comment by ra1nb0w** [comment]
change for codec2 at https://github.com/drowe67/codec2/pull/67

The target is to "connect" with the library.

Both patches tested on macports, with make install and with instruction on README.
Anyway, circular dependency is not good to manage especially with package manager.

**Comment by ra1nb0w** [comment]
thank you!

**Pull request merged**
