### PR TITLE
Add CPack configuration for Debian packaging.

### PR DESCRIPTION
**Pull request by tmiw**
LPCNet equivalent to drowe67/codec2#169 and drowe67/freedv-gui#87.

### CODE REVIEW

**Comment by hobbes1069** [comment]
Doesn't bother me any as I'm a Fedora guy but I have noticed that on the RPM distro side that the artifacts produced are not of high quality even if they "work".  I don't know if this is a deficiency in CMake or whoever setup CPack. Obviously I'm looking at this in a pretty pedantic way as a packager.

**Comment by tmiw** [comment]
@hobbes1069, @drowe67 and I are going to check with AA4HS and see what he thinks about the Debian side since he's worked on those packages before. There might be a way to ensure that the generated packages are still acceptable.

**Comment by tmiw** [comment]
@hobbes1069, @drowe67, seems that Debian uses a different mechanism for producing packages but these PRs shouldn't interfere I think. 

BTW, I figured out how to generate separate -dev, etc. packages and use Debian standard naming and updated the PRs accordingly.

**Comment by drowe67** [comment]
Thanks @tmiw just let me know when you are ready to merge the CPack series of PRs...

**Comment by tmiw** [comment]
@drowe67, I think we're good if the README.md changes I just pushed look fine. 👍

**Pull request merged**
