### PR TITLE
Davids 2020 and Travis branch

### PR DESCRIPTION
**Pull request by drowe67**
Work in progress branch for Travis and FreeDV 2020 work

### CODE REVIEW

**Comment by drowe67** [comment]
@hobbes1069 I've added Travis in this branch, note how "the pull request" build is not passing.  You can use this .travis.yml as a way to test your builds, Travis uses Xenial (Ubuntu 16).

**Comment by hobbes1069** [comment]
Ok, before I go changing a bunch of Travis CI stuff... 

1. If we use the -D<PROJECT>_BUILD_DIR method we don't need to install either library.
2. I think I see part of the problem. I've been making my commits to brad-2020 and you have it checking out dr-2020... The required exports (cmake files for find_package) are not exported with dr-2020.

**Comment by drowe67** [comment]
Hi Richard,

Moving forward, I see us using the cmake design you are working on in LPCNet/master and codec2/brad-2020.

The LPCNet/dr-2020 and codec2/dr-2020 branches are snap shots from a week ago that provide a working LPCNet & codec2 baseline Brad and I can use to progress FreeDV 2020 integration, while you resolve the cross platform cmake issues we are experiencing in LPCNet/master and codec2/brad-2020.

I'd like to use Travis to verify the cmake system on an Ubuntu system.  It's a really good way to take humans out of the test loop. The .travis.yml file here might be a good starting point, but modified for your cmake system design.  I'm happy to help you code this up for LPCNet/master codec2/brad-2020 if you like.

**Comment by hobbes1069** [comment]
ok, I read it twice but still not sure what to do. If we want this one to pass Travis CI we'll at least need to git cherry-pick the export parts from brad-2020.

**Comment by drowe67** [comment]
> ok, I read it twice but still not sure what to do. If we want this one to pass Travis CI we'll at least need to git cherry-pick the export parts from brad-2020.

Sorry my initial comment https://github.com/drowe67/LPCNet/pull/3#issuecomment-484746291 wasn't well written:

1. It's not necessary to get the Travis Pull Request build to pass in this branch.  I accept that won't pass as this branch is using as different cmake system design to LPCNet/master.  That's OK.

2. Pls don't modify anything in this branch - we need it stable for FreeDV 2020 work.

3. Pls add Travis support to LPCNet/master and codec2/brad-2020, to support the testing of the cmake system in those branches.  You are welcome to use the .travis.yml file in this branch as a starting point.  Actually codec2/brad-2020 probably has Travis support already, this would just need extending to exercise the LPCNet/2020 build.

**Comment by drowe67** [comment]
No required any more as LPCNet/master is working well

**Pull request closed without merging**
