### PR TITLE
Small changes to enable compilation under OSX

### PR DESCRIPTION
**Pull request by darksidelemm**
A few changes to the cmake file and idct.c to enable detection of processor optimizations and build under OSX.

Re-based with the master branch, so hopefully this will kick off a travis run.

### CODE REVIEW

**Comment by drowe67** [comment]
Nice work @darksidelemm 

Would you like me to merge? Or we can keep it open if you have other plans you would like to try.

**Comment by drowe67** [comment]
I'll also get @hobbes1069 to review

**Comment by hobbes1069** [comment]
I don't see any problems with the cmake logic however, CMake's internally uses "APPLE". Without a darwin system available I can't test what system macros are defined though. 

I've seen another approach used on other projects:
```
if(UNIX AND NOT APPLE)
    <*nix stuff>
else()
    <macosx stuff>
endif()
```

**Comment by hobbes1069** [comment]
Mark, I'd like your feedback first but I think your update to idct.c is no longer needed with the commit to change uint to unsigned int.  I would also like to know if the "UNIX AND NOT APPLE method works properly as I think it's a bit cleaner.

**Comment by darksidelemm** [comment]
OK, I've made that change and rebased. It compiles on my OSX system, and the travis tests pass.

**Comment by hobbes1069** [comment]
That should work, although the elseif is superfluous since the else() would already be equivalent to UNIX AND APPLE and since it's derived from NEXT it's considered *nix.

**Review by hobbes1069 — APPROVED** [review]

**Pull request merged**
